import { ListingDTO, SiteSettingDTO } from '@/types';

export const fallbackSettings: SiteSettingDTO = {
  id: 'default',
  siteName: 'İLAN VİTRİNİ',
  logoUrl: null,
  faviconUrl: null,
  mainWhatsApp: '905392624086',
  mainPhone: '05392624086',
  instagramUrl: null,
  telegramUrl: null,
  footerText: 'Vitrin İlan Portalı © 2026 Tüm hakları saklıdır.',
  ctaTitle: 'İLAN VERMEK İÇİN TIKLAYIN',
  ctaSubtitle: 'WhatsApp üzerinden hemen iletişime geçin, ilanınızı birkaç dakikada yayınlayın.',
  ctaButtonText: "WHATSAPP'TAN ULAŞIN",
  ctaActive: true,
  seoTitle: 'İzmir, Aydın, Manisa, Denizli Escort & Masaj Rehberi - Güncel Esc Vitrini',
  seoDescription:
    'İzmir escort, Aydın escort, Manisa escort, Denizli escort ve masaj ilanları. Kendi yeri olan, kendi yeri yok otele gelen bayanlar ve VIP esc masaj profilleri ile doğrudan WhatsApp iletişimi.',
  googleAnalyticsId: null,
  maintenanceMode: false,
};

const now = new Date().toISOString();

export const fallbackListings: ListingDTO[] = [
  {
    id: 'demo-1',
    name: 'MISRA',
    slug: 'misra-izmir-100',
    cityId: 'c-izmir',
    city: { id: 'c-izmir', name: 'İzmir', slug: 'izmir' },
    district: 'Alsancak',
    description:
      'Alsancak merkezde lüks kendi yerimde misafir etmekteyim. VIP masaj ve samimi görüşmeler için WhatsApp üzerinden ulaşabilirsiniz.',
    phone: '05392624086',
    whatsapp: '905392624086',
    venueType: 'KENDİ YERİ VAR',
    paymentType: 'ELDEN ÖDEME',
    tags: 'İzmir Escort,Alsancak,Kendi Yeri Var,VIP Masaj',
    featured: true,
    active: true,
    sortOrder: 1,
    viewCount: 142,
    createdAt: now,
    updatedAt: now,
    images: [
      {
        id: 'img-1-1',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img-1-2',
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img-1-3',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
        sortOrder: 2,
        isCover: false,
      },
      {
        id: 'img-1-4',
        url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
        sortOrder: 3,
        isCover: false,
      },
    ],
  },
  {
    id: 'demo-2',
    name: 'İRANLI MEYRA',
    slug: 'meyra-aydin-101',
    cityId: 'c-aydin',
    city: { id: 'c-aydin', name: 'Aydın', slug: 'aydin' },
    district: 'Kuşadası',
    description:
      'Orijinal fotoğraflar. Kendi yerim yok, sadece otel veya rezidans randevularına geliyorum. Hijyen ve gizlilik esastır.',
    phone: '05392624086',
    whatsapp: '905392624086',
    venueType: 'KENDİ YERİ YOK',
    paymentType: 'ELDEN ÖDEME',
    tags: 'Aydın Escort,Kuşadası,Kendi Yeri Yok,Otel,Rezidans',
    featured: true,
    active: true,
    sortOrder: 2,
    viewCount: 98,
    createdAt: now,
    updatedAt: now,
    images: [
      {
        id: 'img-2-1',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img-2-2',
        url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img-2-3',
        url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
        sortOrder: 2,
        isCover: false,
      },
      {
        id: 'img-2-4',
        url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80',
        sortOrder: 3,
        isCover: false,
      },
    ],
  },
  {
    id: 'demo-3',
    name: 'PERİ',
    slug: 'peri-izmir-102',
    cityId: 'c-izmir',
    city: { id: 'c-izmir', name: 'İzmir', slug: 'izmir' },
    district: 'Bornova',
    description:
      'Bornova metroya yakın konforlu ve bağımsız kendi yerim var. Rahatlatıcı masaj ve güler yüzlü hizmet.',
    phone: '05342982882',
    whatsapp: '905342982882',
    venueType: 'KENDİ YERİ VAR',
    paymentType: 'ELDEN ÖDEME',
    tags: 'İzmir Escort,Bornova,Kendi Yeri Var,Masaj',
    featured: false,
    active: true,
    sortOrder: 3,
    viewCount: 84,
    createdAt: now,
    updatedAt: now,
    images: [
      {
        id: 'img-3-1',
        url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img-3-2',
        url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img-3-3',
        url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
        sortOrder: 2,
        isCover: false,
      },
      {
        id: 'img-3-4',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
        sortOrder: 3,
        isCover: false,
      },
    ],
  },
  {
    id: 'demo-4',
    name: 'AYBÜKE',
    slug: 'aybuke-manisa-103',
    cityId: 'c-manisa',
    city: { id: 'c-manisa', name: 'Manisa', slug: 'manisa' },
    district: 'Şehzadeler',
    description:
      'Manisa merkez otel görüşmelerine geliyorum. Kendi yerim yok, elit beylerle randevu almaktayım.',
    phone: '05389112233',
    whatsapp: '905389112233',
    venueType: 'KENDİ YERİ YOK',
    paymentType: 'ELDEN ÖDEME',
    tags: 'Manisa Escort,Şehzadeler,Kendi Yeri Yok,Otele Gelir',
    featured: false,
    active: true,
    sortOrder: 4,
    viewCount: 65,
    createdAt: now,
    updatedAt: now,
    images: [
      {
        id: 'img-4-1',
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img-4-2',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img-4-3',
        url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
        sortOrder: 2,
        isCover: false,
      },
      {
        id: 'img-4-4',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
        sortOrder: 3,
        isCover: false,
      },
    ],
  },
  {
    id: 'demo-5',
    name: 'BETÜL',
    slug: 'betul-denizli-104',
    cityId: 'c-denizli',
    city: { id: 'c-denizli', name: 'Denizli', slug: 'denizli' },
    district: 'Pamukkale',
    description:
      'Denizli Pamukkale bölgesinde nezih ve ferah kendi yerim var. Aromaterapi ve rahatlatıcı masaj seansları.',
    phone: '05378445566',
    whatsapp: '905378445566',
    venueType: 'KENDİ YERİ VAR',
    paymentType: 'ELDEN ÖDEME',
    tags: 'Denizli Escort,Pamukkale,Kendi Yeri Var,Masaj',
    featured: false,
    active: true,
    sortOrder: 5,
    viewCount: 52,
    createdAt: now,
    updatedAt: now,
    images: [
      {
        id: 'img-5-1',
        url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img-5-2',
        url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=600&q=80',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img-5-3',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
        sortOrder: 2,
        isCover: false,
      },
    ],
  },
  {
    id: 'demo-6',
    name: 'BİREYSEL ECEM',
    slug: 'ecem-izmir-105',
    cityId: 'c-izmir',
    city: { id: 'c-izmir', name: 'İzmir', slug: 'izmir' },
    district: 'Karşıyaka',
    description:
      'Karşıyaka sahilde bağımsız, temiz ve güvenli daire. Bireysel kaliteli görüşmeler.',
    phone: '05449635815',
    whatsapp: '905449635815',
    venueType: 'KENDİ YERİ VAR',
    paymentType: 'ELDEN ÖDEME',
    tags: 'İzmir Esc,Karşıyaka,Bireysel,Elden Ödeme',
    featured: true,
    active: true,
    sortOrder: 6,
    viewCount: 110,
    createdAt: now,
    updatedAt: now,
    images: [
      {
        id: 'img-6-1',
        url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=600&q=80',
        sortOrder: 0,
        isCover: true,
      },
      {
        id: 'img-6-2',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
        sortOrder: 1,
        isCover: false,
      },
      {
        id: 'img-6-3',
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80',
        sortOrder: 2,
        isCover: false,
      },
      {
        id: 'img-6-4',
        url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80',
        sortOrder: 3,
        isCover: false,
      },
    ],
  },
];
